stages:
  - build

build_job:
  stage: build
  script:
  - security default-keychain -s "/opt/buildRoot/xcbuild.keychain"
  - security unlock-keychain -p "${keychain_password}" "/opt/buildRoot/xcbuild.keychain"
  - rm -rf bilibili/APIKey.h;
  - echo "NSString *APIKey = @\"${APIKey}\";" >> bilibili/APIKey.h;
  - echo "NSString *APISecret = @\"${APISecret}\";" >> bilibili/APIKey.h;
  - git submodule update --init
  - rm -rf bilibili/libs
  - cp -r /opt/buildRoot/libs bilibili/libs
  - xctool -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - ditto -c -k --sequesterRsrc Build/Products/Release/Bilibili.app Build/Products/Release/Application.zip
  - codesign -s "Developer ID Application" --keychain "/opt/buildRoot/xcbuild.keychain" --deep --force "Build/Products/Release/Application.zip"
  - rm -rf Build/Products/Release/*.framework
  - rm -rf Build/Products/Release/*.app
  - security default-keychain -s "login.keychain"

cache:
  untracked: false